/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JSLG
 */
public class DialogBuscar extends javax.swing.JDialog {

    DefaultTableModel modelo;
    
    public DialogBuscar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("No Pagina");
        modelo.addColumn("Nombres Difunto");
        modelo.addColumn("Apellidos");
        modelo.addColumn("No Cedula");
        modelo.addColumn("Fecha defuncion");
        modelo.addColumn("Nombre Responsable");
        modelo.addColumn("Apellidos");
        modelo.addColumn("No Cedula");
        modelo.addColumn("Direccion");
        modelo.addColumn("Pago terreno");
        modelo.addColumn("Pago Cepultura");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BuscarDifunto = new javax.swing.JTextField();
        BuscarCodigo = new javax.swing.JTextField();
        FDefuncion1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BuscarDifunto1 = new javax.swing.JTextField();
        FDefuncion2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Captura.PNG"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1060, 120);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Pagina", " Difunto", "Apellido", "Cedula", " Defuncion", " Responsable", "Apellido", "Cedula", "Terreno", "Cepultura"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(0, 102, 255));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(100);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(1).setMinWidth(100);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(290, 180, 760, 330);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)), "Busqueda Responsable", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 220, 260, 120);

        jLabel4.setText("Nombres");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 250, 50, 14);

        jLabel5.setText("Defuncion");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 280, 50, 20);

        jLabel6.setText("Codigo");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 310, 40, 14);

        BuscarDifunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarDifuntoActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarDifunto);
        BuscarDifunto.setBounds(80, 250, 180, 20);

        BuscarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarCodigo);
        BuscarCodigo.setBounds(80, 310, 180, 20);

        FDefuncion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FDefuncion1ActionPerformed(evt);
            }
        });
        getContentPane().add(FDefuncion1);
        FDefuncion1.setBounds(80, 280, 180, 20);

        jLabel7.setText("Nombres");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 390, 50, 14);

        jLabel8.setText("No Cedula");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 420, 50, 20);

        BuscarDifunto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarDifunto1ActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarDifunto1);
        BuscarDifunto1.setBounds(80, 390, 180, 20);

        FDefuncion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FDefuncion2ActionPerformed(evt);
            }
        });
        getContentPane().add(FDefuncion2);
        FDefuncion2.setBounds(80, 420, 180, 20);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)), "Busqueda Responsable", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 360, 260, 100);

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(80, 480, 130, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("   Llene uno de los campos del formulario de busqueda del difunto o del formulario de busqueda del reponsable.");
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255)));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(310, 140, 685, 21);

        jLabel1.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("  FORMULARIOS DE BUSQUEDA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 180, 250, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarCodigoActionPerformed

    private void BuscarDifuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarDifuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarDifuntoActionPerformed

    private void FDefuncion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDefuncion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FDefuncion1ActionPerformed

    private void BuscarDifunto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarDifunto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarDifunto1ActionPerformed

    private void FDefuncion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDefuncion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FDefuncion2ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogBuscar dialog = new DialogBuscar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BuscarCodigo;
    private javax.swing.JTextField BuscarDifunto;
    private javax.swing.JTextField BuscarDifunto1;
    private javax.swing.JTextField FDefuncion1;
    private javax.swing.JTextField FDefuncion2;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
