/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import models.Difunto;
import models.Registro;
import models.Responsable;
import models.Terreno;

/**
 *
 * @author Ervin
 */
public class FrameRegistroNuevo extends javax.swing.JFrame {
    ArrayList<Registro> registros = new ArrayList<Registro>();
    Registro RG = new Registro("1","",null,null,null);

    /**
     * Creates new form FrameRegistroNuevo
     */
    public FrameRegistroNuevo() {
        initComponents();
        this.setExtendedState(0);
        this.setLocationRelativeTo(null);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDatosResponsable = new javax.swing.JLabel();
        lbDatosDifunto1 = new javax.swing.JLabel();
        lbDatosGenerales = new javax.swing.JLabel();
        lbEncabezado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtNoPagina = new javax.swing.JTextField();
        txtApellidosDifunto = new javax.swing.JTextField();
        txtNomResponsable = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbDatosPago = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCedulaResponsable = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPagoTerreno = new javax.swing.JTextField();
        txtPagoCepultura = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnSAlir = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNomDifunto = new javax.swing.JTextField();
        txtCedulaDifunto = new javax.swing.JFormattedTextField();
        txtFechaDefuncion = new javax.swing.JFormattedTextField();
        txtApellidoResponsable = new javax.swing.JLabel();
        txtAPELLIDOSResponsable = new javax.swing.JTextField();
        lbDatosPago1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtPagoTerreno1 = new javax.swing.JTextField();
        txtPagoCepultura1 = new javax.swing.JTextField();
        btnGuardar1 = new javax.swing.JButton();
        btnSAlir1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtPagoTerreno2 = new javax.swing.JTextField();
        btnGuardar2 = new javax.swing.JButton();
        btnSAlir2 = new javax.swing.JButton();

        lbDatosResponsable.setBackground(new java.awt.Color(255, 255, 255));
        lbDatosResponsable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDatosResponsable.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)), "Datos Del Responsable", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        lbDatosDifunto1.setBackground(new java.awt.Color(255, 255, 255));
        lbDatosDifunto1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDatosDifunto1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)), "Datos Del Difunto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        lbDatosGenerales.setBackground(new java.awt.Color(255, 255, 255));
        lbDatosGenerales.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDatosGenerales.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)), "Datos Generales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(null);

        lbEncabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Captura (4).png"))); // NOI18N
        getContentPane().add(lbEncabezado);
        lbEncabezado.setBounds(0, 0, 1945, 90);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("No Pagina:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 131, 65, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Fecha:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 161, 38, 15);
        getContentPane().add(txtFecha);
        txtFecha.setBounds(90, 161, 130, 20);
        getContentPane().add(txtNoPagina);
        txtNoPagina.setBounds(90, 131, 130, 20);
        getContentPane().add(txtApellidosDifunto);
        txtApellidosDifunto.setBounds(90, 290, 240, 20);

        txtNomResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomResponsableActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomResponsable);
        txtNomResponsable.setBounds(100, 380, 260, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("No Cedula:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 250, 65, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Apellidos:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 290, 59, 15);

        lbDatosPago.setBackground(new java.awt.Color(255, 255, 255));
        lbDatosPago.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDatosPago.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)), "Datos De Pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12), new java.awt.Color(0, 0, 255))); // NOI18N
        getContentPane().add(lbDatosPago);
        lbDatosPago.setBounds(10, 885, 657, 100);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Nombres:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 380, 57, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("No Cedula:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(380, 410, 65, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Dirección:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 440, 59, 15);

        txtCedulaResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaResponsableActionPerformed(evt);
            }
        });
        getContentPane().add(txtCedulaResponsable);
        txtCedulaResponsable.setBounds(460, 410, 190, 20);
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(100, 440, 550, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Pago de terreno de cepultura:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 915, 185, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Pago permiso de cepultura:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 945, 168, 20);
        getContentPane().add(txtPagoTerreno);
        txtPagoTerreno.setBounds(240, 915, 400, 20);
        getContentPane().add(txtPagoCepultura);
        txtPagoCepultura.setBounds(240, 945, 400, 20);

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 204));
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(149, 991, 150, 30);

        btnSAlir.setBackground(new java.awt.Color(255, 255, 255));
        btnSAlir.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnSAlir.setForeground(new java.awt.Color(0, 51, 204));
        btnSAlir.setText("SALIR");
        btnSAlir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        btnSAlir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAlirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSAlir);
        btnSAlir.setBounds(384, 991, 160, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Fecha defunción:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(350, 290, 103, 15);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Nombres:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 250, 57, 15);

        txtNomDifunto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomDifuntoKeyTyped(evt);
            }
        });
        getContentPane().add(txtNomDifunto);
        txtNomDifunto.setBounds(90, 250, 240, 20);

        txtCedulaDifunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaDifuntoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCedulaDifunto);
        txtCedulaDifunto.setBounds(440, 250, 190, 20);
        getContentPane().add(txtFechaDefuncion);
        txtFechaDefuncion.setBounds(470, 290, 160, 20);

        txtApellidoResponsable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtApellidoResponsable.setText("Apellidos:");
        getContentPane().add(txtApellidoResponsable);
        txtApellidoResponsable.setBounds(30, 410, 59, 15);

        txtAPELLIDOSResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAPELLIDOSResponsableActionPerformed(evt);
            }
        });
        getContentPane().add(txtAPELLIDOSResponsable);
        txtAPELLIDOSResponsable.setBounds(100, 410, 260, 20);

        lbDatosPago1.setBackground(new java.awt.Color(255, 255, 255));
        lbDatosPago1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDatosPago1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)), "Datos De Pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12), new java.awt.Color(0, 0, 255))); // NOI18N
        getContentPane().add(lbDatosPago1);
        lbDatosPago1.setBounds(0, 0, 10, 21);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Pago de terreno de cepultura:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, 0, 185, 15);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Pago permiso de cepultura:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 0, 168, 15);
        getContentPane().add(txtPagoTerreno1);
        txtPagoTerreno1.setBounds(0, 0, 6, 20);
        getContentPane().add(txtPagoCepultura1);
        txtPagoCepultura1.setBounds(0, 0, 6, 20);

        btnGuardar1.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnGuardar1.setForeground(new java.awt.Color(0, 0, 204));
        btnGuardar1.setText("GUARDAR");
        btnGuardar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar1);
        btnGuardar1.setBounds(0, 0, 65, 19);

        btnSAlir1.setBackground(new java.awt.Color(255, 255, 255));
        btnSAlir1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnSAlir1.setForeground(new java.awt.Color(0, 51, 204));
        btnSAlir1.setText("SALIR");
        btnSAlir1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true));
        btnSAlir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAlir1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSAlir1);
        btnSAlir1.setBounds(0, 0, 41, 19);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Pago de terreno de cepultura:");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(30, 490, 185, 15);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Pago permiso de cepultura:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(20, 535, 170, 20);
        getContentPane().add(txtPagoTerreno2);
        txtPagoTerreno2.setBounds(240, 480, 170, 20);

        btnGuardar2.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnGuardar2.setForeground(new java.awt.Color(0, 0, 204));
        btnGuardar2.setText("GUARDAR");
        btnGuardar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        btnGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar2);
        btnGuardar2.setBounds(310, 580, 65, 19);

        btnSAlir2.setBackground(new java.awt.Color(255, 255, 255));
        btnSAlir2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnSAlir2.setForeground(new java.awt.Color(0, 51, 204));
        btnSAlir2.setText("SALIR");
        btnSAlir2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true));
        btnSAlir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAlir2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSAlir2);
        btnSAlir2.setBounds(200, 590, 41, 19);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomResponsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomResponsableActionPerformed

    private void txtCedulaResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaResponsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaResponsableActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(ValidacionObligatoria() == false){
            JOptionPane.showMessageDialog(null,"El nombre del responsable es obligatorio","CAMPO OBLIGATORIO",JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            Difunto D = new Difunto();
            D.setNombres(txtNomDifunto.getText());
            D.setApellidos(txtApellidosDifunto.getText());
            D.setFechaDefuncion(txtFechaDefuncion.getText());
            D.setNoCedula(txtCedulaDifunto.getText());
            Responsable R = new Responsable();
            R.setNombres(txtNomResponsable.getText());
            R.setApellidos(txtAPELLIDOSResponsable.getText());
            R.setDireccion(txtDireccion.getText());
            R.setNoCedula(txtCedulaResponsable.getText());
            Terreno T = new Terreno();
            String codigo = txtFechaDefuncion.getText() + "-" + (registros.size()+1);
            T.setCodigo(codigo);
            T.setPagoSepultura(Integer.parseInt(txtPagoCepultura.getText()));
            T.setPagoTerreno(Integer.parseInt(txtPagoTerreno.getText()));
            
                    
            Registro RG = new Registro(codigo,"",D,R,T);
            System.out.println(RG.getCodigo());
            registros.add(RG);
            Limpiar();
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtCedulaDifuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaDifuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaDifuntoActionPerformed

    private void txtAPELLIDOSResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAPELLIDOSResponsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAPELLIDOSResponsableActionPerformed

    private void btnSAlirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAlirActionPerformed
        //System.exit(0);
        this.dispose();
    }//GEN-LAST:event_btnSAlirActionPerformed

    private void txtNomDifuntoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomDifuntoKeyTyped
        soloLetras(evt);
    }//GEN-LAST:event_txtNomDifuntoKeyTyped

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed

    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void btnSAlir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAlir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSAlir1ActionPerformed

    private void btnGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar2ActionPerformed

    }//GEN-LAST:event_btnGuardar2ActionPerformed

    private void btnSAlir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAlir2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSAlir2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRegistroNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRegistroNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRegistroNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRegistroNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRegistroNuevo().setVisible(true);
            }
        });
    }
    
    
    public boolean ValidacionObligatoria(){
        if(txtNomResponsable.getText().isEmpty() == true || txtAPELLIDOSResponsable.getText().isEmpty() == true){
            
            return false;
        }
        return true;
    
}
    public void Limpiar(){
        txtNomDifunto.setText("");
        txtApellidosDifunto.setText("");
        txtCedulaDifunto.setText("");
        txtFechaDefuncion.setText("");
        
        txtNomResponsable.setText("");
        txtAPELLIDOSResponsable.setText("");
        txtDireccion.setText("");
        txtCedulaResponsable.setText("");
        
        txtPagoTerreno.setText("");
        txtPagoCepultura.setText("");
    }
    
    public void soloLetras(KeyEvent evt){
        if(Character.isLetter(evt.getKeyChar()) != true){
            evt.consume();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnGuardar2;
    private javax.swing.JButton btnSAlir;
    private javax.swing.JButton btnSAlir1;
    private javax.swing.JButton btnSAlir2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbDatosDifunto1;
    private javax.swing.JLabel lbDatosGenerales;
    private javax.swing.JLabel lbDatosPago;
    private javax.swing.JLabel lbDatosPago1;
    private javax.swing.JLabel lbDatosResponsable;
    private javax.swing.JLabel lbEncabezado;
    private javax.swing.JTextField txtAPELLIDOSResponsable;
    private javax.swing.JLabel txtApellidoResponsable;
    private javax.swing.JTextField txtApellidosDifunto;
    private javax.swing.JFormattedTextField txtCedulaDifunto;
    private javax.swing.JTextField txtCedulaResponsable;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JFormattedTextField txtFechaDefuncion;
    private javax.swing.JTextField txtNoPagina;
    private javax.swing.JTextField txtNomDifunto;
    private javax.swing.JTextField txtNomResponsable;
    private javax.swing.JTextField txtPagoCepultura;
    private javax.swing.JTextField txtPagoCepultura1;
    private javax.swing.JTextField txtPagoTerreno;
    private javax.swing.JTextField txtPagoTerreno1;
    private javax.swing.JTextField txtPagoTerreno2;
    // End of variables declaration//GEN-END:variables
}
